auth0-samples/auth0-react-samples

- 05-Token-Renewal/silent.html
- 05-Token-Renewal/src/Auth/Auth.js
https://github.com/auth0/auth0.js/issues/406
> fix silent auth: messages not from auth0 iframe

- 01-Login/src/Auth/Auth.js
- 02-User-Profile/src/Auth/Auth.js
- 03-Calling-an-API/src/Auth/Auth.js
- 04-Authorization/src/Auth/Auth.js
- 05-Token-Renewal/src/Auth/Auth.js
Clear session at Auth0 authorization server calling `/v2/logout` endpoint when perform logout.
> Logout from Auth0 authorization server

- 01-Login/src/Auth/Auth.js
- 02-User-Profile/src/Auth/Auth.js
- 03-Calling-an-API/src/Auth/Auth.js
- 04-Authorization/src/Auth/Auth.js
- 05-Token-Renewal/src/Auth/Auth.js
Hi @lbalmaceda fixed the return to parameter for the samples. I had also opened another one for angular [here](https://github.com/auth0-samples/auth0-angular-samples/pull/144). Wrong parameter seems to be applied to multiple samples. Would it be possible to merge these requests?
> fix for the return to parameter

- 01-Login/package-lock.json
- 01-Login/package.json
- 01-Login/src/Home/Home.js
- 02-User-Profile/package-lock.json
- 02-User-Profile/package.json
- 03-Calling-an-API/package-lock.json
- 03-Calling-an-API/package.json
- 04-Authorization/package-lock.json
- 04-Authorization/package.json
- 05-Token-Renewal/package-lock.json
- 05-Token-Renewal/package.json
- 05-Token-Renewal/src/Auth/auth0-variables.js.example
Bumped versioning for REact. Also notice that the vulnerabilities that are not fixed by facebook.
https://github.com/facebook/react/issues/14868
https://github.com/facebook/react/issues/15470
> Fix [QS-97]: Vulnerabilities in React QS

- .circleci/config.yml
- 01-Login/src/Auth/Auth.js
- 01-Login/src/Auth/auth0-variables.js.example
- 02-User-Profile/src/Auth/Auth.js
- 02-User-Profile/src/Auth/auth0-variables.js.example
- 03-Calling-an-API/src/Auth/Auth.js
- 03-Calling-an-API/src/Auth/auth0-variables.js.example
- 04-Authorization/src/Auth/Auth.js
- 04-Authorization/src/Auth/auth0-variables.js.example
- 05-Token-Renewal/src/Auth/Auth.js
- 05-Token-Renewal/src/Auth/auth0-variables.js.example
Fixes issue #105 
Makes all of the clientID references consistent across the solution
> Make all of the clientID references consistent

- 01-Login/README.md
- 02-User-Profile/README.md
- 03-Calling-an-API/README.md
- 04-Authorization/README.md
- 05-Token-Renewal/README.md
In preparation for the new sample docs to hit.
> Migration of React tutorials from /docs

- 01-Login/exec.ps1
- 01-Login/package.json
- 01-Login/server.js
- 02-Calling-an-API/Dockerfile
- 02-Calling-an-API/exec.ps1
- 02-Calling-an-API/exec.sh
- 02-Calling-an-API/package.json
- 02-Calling-an-API/server.js
Refactoring the dependencies so that the sample can run with everything is needs with `NODE_ENV=production` outside of a Docker container.
For sample 02, this also means a slight refactor for the scripts in `package.json` and how `server.js` behaves.
> Dependency refactor

- 01-Login/public/index.html
- 01-Login/src/App.js
- 01-Login/src/components/Content.js
- 01-Login/src/components/Footer.js
- 01-Login/src/components/Hero.js
- 01-Login/src/components/NavBar.js
- 01-Login/src/utils/initFontAwesome.js
- 01-Login/src/views/Profile.js
- 02-Calling-an-API/public/index.html
- 02-Calling-an-API/src/App.css
- 02-Calling-an-API/src/App.js
- 02-Calling-an-API/src/components/Content.js
- 02-Calling-an-API/src/components/Footer.js
- 02-Calling-an-API/src/components/Hero.js
- 02-Calling-an-API/src/components/NavBar.js
- 02-Calling-an-API/src/utils/initFontAwesome.js
- 02-Calling-an-API/src/views/Profile.js
* Various classes added that make the sample look more consistant using only Bootstrap vs. Bootstrap + our theme
* Included Bootstrap as a dependency (in preparation for auth0-quickstarts/samples-bootstrap-theme#2)
> Updates to the quickstart theme

- 01-Login/src/components/PrivateRoute.js
- 02-Calling-an-API/src/components/PrivateRoute.js
This change was made to bring the sample inline with a change in the docs.
For reference: https://github.com/auth0/docs/pull/7932/files
> Prevented PrivateRoute from briefly showing page when unauthenticated

- 01-Login/README.md
- 02-Calling-an-API/README.md
> Added link to SDK FAQ page

- .gitignore
- 01-Login/package-lock.json
- 01-Login/src/components/PrivateRoute.js
- 02-Calling-an-API/src/components/PrivateRoute.js
Without WithRouter and location, when you redirect after authentication if a route has a params in the path, it won't  redirect correctly (a route like this identity/:id/ ...) won't work
> Add redirect fix for react router

- 01-Login/src/components/PrivateRoute.js
- 02-Calling-an-API/src/components/PrivateRoute.js
`PrivateRoute.js` should match https://auth0.com/docs/quickstart/spa/react#secure-the-profile-page
> [QS-327] Update PrivateRoute.js to match Quickstart

- Sample-01/README.md
> Update readme with information about creating an API

- Sample-01/README.md
> Fix use case links in Readme file

- Sample-01/api-server.js
- Sample-01/package.json
- Sample-01/yarn.lock
* Updates express-jwt dep
* Fixes options sent to express-jwt
* Tested in sample app with postman
> Fixes vulnerability in express-jwt 

- Sample-01/README.md
* Correct the link to the right FAQ
* Tweaked the wording to better guide the user to the FAQ if they have problems refreshing auth state on page refresh (a very common problem)
Ref: #215
> Update sample readme with link to auth0-react FAQ

- Sample-01/src/index.js
> Add a comment to point to provider options

- Sample-01/yarn.lock
This PR updates the `yarn.lock` file to resolve vulnerabilities identified in previous versions of a number of project dependencies.
> Security: Update sample dependencies lockfile

- Sample-01/package-lock.json
- Sample-01/yarn.lock
This PR updates `Gemfile.lock` to reflect latest dependency versions, and resolves Snyk warnings.
> chore: Update Dependencies Lockfile

- Sample-01/package.json
- Sample-01/src/components/NavBar.js
- Sample-01/src/index.js
- Sample-01/yarn.lock
Merges the beta branch into master, should be updated once we've published `@auth0/auth0-react@2.0.0` before merge
> Merge beta sample into master

- Sample-01/server.js
In dev mode `react-scripts` does this for you
> Fix routing from the address bar in prod mode

- README.md
- Sample-01/public/index.html
- netlify.toml
Added netlify.toml to simplify the deployment of this QS as a Netlify website.
> added netlify.toml file
